### ISSUE TITLE
Project Values

### ISSUE THREAD

**Issue by SchwartzTP** [USStateDept/bids#249]
I've gotten a lot of comments from a number of posts about the project value requirement.  It seems that there are a number of countries around the world that do not normally include an estimate for project value in their tender documents.  One post reports that they asked procurement authorities about this and were told this is a long standing policy; they don't want to suggest a final price to potential vendors.  When I went back to posts and suggested they "Guesstimate" a project value (and then note in the post comments that the value was an estimate by post), I got a number of well reasoned objections (nothing to compare it to, lack of knowledge of the field, etc.)
I'm wondering if a solution would be to include a radio button where posts could either select to enter a project value, or select "No Project Value Provided by Implementing Agency" or something like that.

**Comment by brodydittemore** [comment]
@SchwartzTP, we will be pushing a few updates on 1/26. Probably the most straightforward solution would be to remove the requirement that FSO's include a Project Value. This will keep the form/process shorter.

Any objection?
