### ISSUE TITLE
Problems with Search Filters?

### ISSUE THREAD

**Issue by SchwartzTP** [USStateDept/bids#259]
When I look at the unfiltered map, I see that there are four projects in Chile (i.e. Chile in the country field).  However, when I enter "Chile" in the "Search for..." Box (i.e., the top field in the search filters), every lead disappears from the map.  
I thought that "Search for" box checked every alphanumeric field in the entry for matches, and so would have returned those four entries with "Chile" in the country field.  Why is that not happening?

**Comment by brodydittemore** [comment]
As part of our recent server upgrades and migrations, we updated to a newer version of OpenGeo. Looks like this caused our keyword queries to break.

**Comment by SchwartzTP** [comment]
Keep me up to date on the status; I've written a script for a training video (which I will send along separately) and need to be sure I'm telling folks about things that will work.

**Comment by SchwartzTP** [comment]
Checked this again today and it seems to be resolved.
